version: '3.9'
services:
  owncloud:
    container_name: owncloud_${INSTANCE}
    image: owncloud/server:${VERSION}
    restart: ${RESTART}
    expose:
      - 80
    depends_on:
      - mariadb
      - redis
    environment:
      - OWNCLOUD_DOMAIN=${DOMAIN}
      - OWNCLOUD_DB_TYPE=mysql
      - OWNCLOUD_DB_NAME=owncloud
      - OWNCLOUD_DB_USERNAME=owncloud
      - OWNCLOUD_DB_PASSWORD=${DB_PASSWORD}
      - OWNCLOUD_DB_HOST=mariadb
      - OWNCLOUD_ADMIN_USERNAME=${ADMIN_USERNAME}
      - OWNCLOUD_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - OWNCLOUD_MYSQL_UTF8MB4=true
      - OWNCLOUD_REDIS_ENABLED=true
      - OWNCLOUD_REDIS_HOST=redis
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - /var/node/stacks/owncloud/${INSTANCE}/data:/mnt/data:rw
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      default:
      ocnetwork:
      
  mariadb:
    image: mariadb:${DB_VERSION}
    container_name: owncloud_${INSTANCE}_mariadb
    restart: ${RESTART}
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_SERVER_PASSWORD}
      - MYSQL_USER=owncloud
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=owncloud
    command: ["--max-allowed-packet=128M", "--innodb-log-file-size=64M"]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "--password=owncloud"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - /var/node/stacks/owncloud/${INSTANCE}/mysql:/var/lib/mysql:rw
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      ocnetwork:

  redis:
    image: redis:${CACHE_VERSION}
    container_name: owncloud_${INSTANCE}_redis
    restart: ${RESTART}
    command: ["--databases", "1"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - /var/node/stacks/owncloud/${INSTANCE}/redis:/data:rw
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      ocnetwork:

networks:
  default:
    external: true
    name: node-network
  ocnetwork:
    driver: bridge
