version: '3'
services:
  zabbix-agent:
    container_name: zabbix_agent_${INSTANCE}
    image: zabbix/zabbix-agent2:${VERSION}
    restart: ${RESTART}
    ports:
      - '10050:10050/tcp'
    environment:
      ZBX_HOSTNAME: ${HOSTNAME}
      ZBX_SERVER_HOST: ${SERVER}
    privileged: true
networks:
  default:
    external: true
    name: node-network
