services:
  manager: # reverse proxies does not care about container security they are use for tls termination and dynamically update changes from database
    image: jc21/nginx-proxy-manager:${VERSION:-latest}
    ports:
      - '37080:80/tcp' # http port -> public ip catch all
      - '47443:443/tcp' # https port -> public ip catch all
      - '81:81/tcp' # behind worker proxies via container name (i.e. http://manager:81) or swarm-network
      #- '8000:8000/tcp' # will be forwarded for portainer edge agents
      # Cloudflare Ports, will be forwarded to manager on 404 (https://blog.cloudflare.com/cloudflare-now-supporting-more-ports/https://blog.cloudflare.com/cloudflare-now-supporting-more-ports/)
      #- '8080:80/tcp' # http port -> behind cloudflare 
      #- '8443:443/tcp' # https port -> behind cloudflare 
      #- '37080:80/tcp' # http port -> internal behind worker proxies
      #- '37443:443/tcp' # https port -> internal behind worker proxies 
    environment:
      #DB_SQLITE_FILE: "/data/database.sqlite" # revere proxy need a postgres configuration database accessed by white listed hosts with valid credentials
      #PUID: 1000 #-> NODE_SWARM_MOUNT need root access to overwrite nginx configuration dynamically from database when behind load-balancer to proxy containers and protect applications from common expoits
      #PGID: 1000 #-> NODE_SWARM_MOUNT need root access to overwrite nginx configuration dynamically from database when behind load-balancer to proxy containers and protect applications from common expoits
      # Default Administrator User:
      INITIAL_ADMIN_EMAIL: ${ADMIN_EMAIL:-admin@example.com}
      INITIAL_ADMIN_PASSWORD: ${ADMIN_PASSWORD:-changeme}
      # Postgres parameters:
      DB_POSTGRES_HOST: ${POSTGRES_HOST:-postgres}
      DB_POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      DB_POSTGRES_USER: ${POSTGRES_USER:-postgres}
      DB_POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      DB_POSTGRES_NAME: ${POSTGRES_DB:-nginx}
      # Uncomment this if IPv6 is not enabled on your host
      DISABLE_IPV6: ${DISABLE_IPV6:-true} #IPv4 Only -> IPv6 terminated by worker proxies
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - type: bind
        source: ${NODE_SWARM_MOUNT:-/mnt/swarm/system/nginx}/reverse-proxy/manager
        target: /data # global manager data -> keys.json should be shared on all instances
        bind:
            create_host_path: true
      - type: bind
        source: ${NODE_SWARM_MOUNT:-/mnt/swarm/system/nginx}/reverse-proxy/letsencrypt
        target: /etc/letsencrypt #should be shared on all instances
        bind:
            create_host_path: true
    healthcheck:
      test: ["CMD", "/usr/bin/check-health"]
      interval: 10s
      timeout: 3s
    deploy:
      mode: replicated
      replicas: 1
      labels:
        one.srg.container.image: "reverse-proxy-manager"
      placement:
        constraints:
          - node.role==manager
      update_config:
        parallelism: 1
        delay: 10s
        order: stop-first
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '1'
          memory: 512M

  reverse-proxy: # reverse proxies does not care about container security they are use for tls termination and dynamically update changes from database
    image: jc21/nginx-proxy-manager:${VERSION:-latest}
    ports:
      - '80:80/tcp' # will be forwarded to manager on 404
      - '443:443/tcp' # will be forwarded to manager on 404
      #- '81:81/tcp' # worker nodes dont have an management interface
      # Uncomment this if behind load balancer
      - '8000:8000/tcp' # will be forwarded to manager
      # Cloudflare Ports (https://blog.cloudflare.com/cloudflare-now-supporting-more-ports/https://blog.cloudflare.com/cloudflare-now-supporting-more-ports/)
      - '8080:8080/tcp' # http port -> behind cloudflare will be forwarded to http://manager:37080 on 404
      - '8443:8443/tcp' # https port -> behind cloudflare will be forwarded to https://manager:37443 on 404
    environment:
      # Postgres parameters:
      DB_POSTGRES_HOST: ${POSTGRES_HOST:-postgres}
      DB_POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      DB_POSTGRES_USER: ${POSTGRES_USER:-postgres}
      DB_POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      DB_POSTGRES_NAME: ${POSTGRES_DB:-nginx}
      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: ${DISABLE_IPV6:-true}
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - type: bind
        source: ${MOUNT:-/mnt/swarm/volumes/nginx}/reverse-proxy/data
        target: /data #will be recreated on all nodes
        bind:
            create_host_path: true
      - type: bind
        source: ${NODE_SWARM_MOUNT:-/mnt/swarm/system/nginx}/reverse-proxy/letsencrypt
        target: /etc/letsencrypt #should be shared on all instances
        bind:
            create_host_path: false
      - ${NODE_SWARM_MOUNT:-/mnt/swarm/system/nginx}/manager/data/keys.json:/data/keys.json:ro #should be used on all instances
    healthcheck:
      test: ["CMD", "/usr/bin/check-health"]
      interval: 10s
      timeout: 3s
    deploy:
      mode: replicated
      replicas: ${NODE_SWARM_REPLICAS:-2}
      labels:
        one.srg.container.image: "reverse-proxy"
      placement:
        constraints:
          - node.role==${NODE_SWARM_ROLE:-worker}
      update_config:
        parallelism: 1
        delay: 10s
        order: stop-first
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '1'
          memory: 512M
      
networks:
  default:
    external: true
    name: ${NETWORK:-swarm-network}
