services:
  reverse-proxy-manager:
    container_name: nginx-${INSTANCE:-proxy-manager}
    image: jc21/nginx-proxy-manager:${VERSION:-latest}
    restart: ${RESTART}
    ports:
      - '80:80/tcp'
      - '443:443/tcp'
      - '81:81/tcp'
    environment:
      DB_SQLITE_FILE: "/data/database.sqlite"
      PUID: 1000
      PGID: 1000
      # Default Administrator User:
      INITIAL_ADMIN_EMAIL: ${ADMIN_EMAIL:-admin@example.com}
      INITIAL_ADMIN_PASSWORD: ${ADMIN_PASSWORD:-changeme}
      # Uncomment this if IPv6 is not enabled on your host
      DISABLE_IPV6: ${DISABLE_IPV6:-true}
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - type: bind
        source: ${MOUNT:-/tmp/node/stacks}/nginx/${INSTANCE:-proxy-manager}/data
        target: /data
        bind:
            create_host_path: true
      - type: bind
        source: ${MOUNT:-/tmp/node/stacks}/nginx/${INSTANCE:-proxy-manager}/letsencrypt
        target: /etc/letsencrypt
        bind:
            create_host_path: true
    healthcheck:
      test: ["CMD", "/usr/bin/check-health"]
      interval: 10s
      timeout: 3s
networks:
  default:
    external: true
    name: ${NETWORK:-node-network}
