version: '3'
services:
  nginx-proxy-manager:
    container_name: nginx_${INSTANCE}
    image: jc21/nginx-proxy-manager:${VERSION}
    restart: ${RESTART}
    ports:
      - '80:80/tcp'
      - '443:443/tcp'
      - '81:81/tcp'
    environment:
      PUID: 1000
      PGID: 100
      DB_SQLITE_FILE: "/data/database.sqlite"
      DISABLE_IPV6: ${DISABLE_IPV6}
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /_node/stacks/nginx-proxy-manager/${INSTANCE}/data:/data:rw
      - /_node/stacks/nginx-proxy-manager/${INSTANCE}/letsencrypt:/etc/letsencrypt:rw
networks:
  default:
    external: true
    name: node-network
