version: '3'
services:
  zabbix-proxy:
    container_name: zabbix_proxy_${INSTANCE}
    image: zabbix/zabbix-proxy-sqlite3:${VERSION}
    restart: ${RESTART}
    ports:
      - '10051:10051/tcp'
    environment:
      ZBX_PROXYMODE: ${PROXYMODE}
      ZBX_HOSTNAME: ${HOSTNAME}
      ZBX_SERVER_HOST: ${SERVER}
    volumes:
      - /_node/stacks/zabbix/${INSTANCE}/data:/var/lib/zabbix/db_data:rw
      - /_node/stacks/zabbix/${INSTANCE}/scripts:/usr/lib/zabbix/externalscripts:rw
      - /_node/stacks/zabbix/${INSTANCE}/modules:/var/lib/zabbix/modules:rw
      - /_node/stacks/zabbix/${INSTANCE}/tls:/var/lib/zabbix/enc:rw
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
networks:
  default:
    external: true
    name: node-network
